$: << "#{ENV["CODEPATH"]}/scantron/lib" # FIXME.
require 'scantron'
require 'number_scanner'
require 'range_scanner'
require 'gorilla/scanner'
require 'gorilla/scanners/temperature_scanner'
require 'gorilla/scanners/time_scanner'
require 'gorilla/scanners/volume_scanner'
require 'gorilla/scanners/weight_scanner'
require 'gorilla/scanners/omni_scanner'
